"""Add task assignments table

Revision ID: ed709735ad49
Revises: 708235923b8a
Create Date: 2025-12-31 15:29:29.472043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed709735ad49'
down_revision: Union[str, Sequence[str], None] = '708235923b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_assignments',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )

    # Create indexes for efficient queries
    op.create_index('idx_task_assignments_task_id', 'task_assignments', ['task_id'])
    op.create_index('idx_task_assignments_user_id', 'task_assignments', ['user_id'])

    # Backfill: assign all existing active tasks to all current group members
    op.execute(sa.text("""
        INSERT INTO task_assignments (task_id, user_id, assigned_at)
        SELECT t.id, gm.user_id, NOW()
        FROM tasks t
        INNER JOIN group_members gm ON t.group_id = gm.group_id
        WHERE t.is_active = true
    """))

    op.drop_constraint(op.f('group_members_group_id_fkey'), 'group_members', type_='foreignkey')
    op.drop_constraint(op.f('group_members_user_id_fkey'), 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'group_members', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key(op.f('group_members_user_id_fkey'), 'group_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('group_members_group_id_fkey'), 'group_members', 'groups', ['group_id'], ['id'], ondelete='CASCADE')

    # Drop indexes before dropping table
    op.drop_index('idx_task_assignments_user_id')
    op.drop_index('idx_task_assignments_task_id')

    op.drop_table('task_assignments')
    # ### end Alembic commands ###
